# Temporal Dynamic Configuration for Lanai Production
# See: https://docs.temporal.io/references/dynamic-configuration

limit.maxIDLength:
  - value: 255
    constraints: {}

system.forceSearchAttributesCacheRefreshOnRead:
  - value: true
    constraints: {}

frontend.enableClientVersionCheck:
  - value: true
    constraints: {}

history.defaultActivityRetryPolicy:
  - value:
      InitialIntervalInSeconds: 1
      MaximumIntervalCoefficient: 100.0
      BackoffCoefficient: 2.0
      MaximumAttempts: 3
    constraints: {}

history.defaultWorkflowRetryPolicy:
  - value:
      InitialIntervalInSeconds: 1
      MaximumIntervalCoefficient: 100.0
      BackoffCoefficient: 2.0
      MaximumAttempts: 0
    constraints: {}
